// Standalone autonomous buyer using only Cartwise's machine-readable APIs.
if(!process.env.GEMINI_API_KEY){console.error('❌ GEMINI_API_KEY is not set. This script requires a real LLM to make purchasing decisions.');process.exit(1)}
const base=process.env.CARTWISE_URL||'http://127.0.0.1:8000';
const agentIdentity={agent_id:process.env.BUYER_AGENT_ID||'cartwise-demo-buyer-001',agent_name:'Cartwise Demo Buyer',declared_purpose:'Automated purchasing demo for Razorpay Buildathon'};
async function decide(goal,products){
  const prompt=`You are an autonomous shopping agent acting on this exact goal: ${goal}\nCatalog: ${JSON.stringify(products)}\nEvaluate name, category, description, price, sizes, and stock. Return ONLY JSON with product_id, quantity, size, reasoning. Choose one in-stock product, quantity 1, and a listed size or null.`;
  const model=process.env.GEMINI_MODEL||'gemini-2.5-flash',response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});
  if(!response.ok)throw new Error(`Gemini decision failed: ${response.status} ${await response.text()}`);const data=await response.json(),decision=JSON.parse(data.candidates?.[0]?.content?.parts?.[0]?.text||''),selected=products.find(p=>p.id===decision.product_id);
  if(!selected||selected.stock<1||decision.quantity!==1||!decision.reasoning)throw new Error(`Gemini returned an invalid purchasing decision: ${JSON.stringify(decision)}`);if(decision.size!==null&&!selected.sizes.map(String).includes(String(decision.size)))throw new Error(`Gemini selected invalid size ${decision.size} for ${selected.id}`);
  const match=goal.match(/(?:under|below|less than|up to|max(?:imum)? budget(?: of)?|budget(?: of| is)?)\s*(?:₹|rs\.?|inr)?\s*([0-9,]+)/i);return{...decision,max_budget:match?Number(match[1].replaceAll(',','')):null,decision_source:`Gemini (${model})`};
}
async function negotiate(decision,catalog){const item=catalog.products.find(p=>p.id===decision.product_id);if(!decision.max_budget||item.price<=decision.max_budget)return{};console.log(`Negotiating listed ₹${item.price} down to budget ₹${decision.max_budget}...`);const response=await fetch(`${base}/api/negotiate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:item.id,requested_price:decision.max_budget,quantity:decision.quantity,reasoning:decision.reasoning,agent_identity:agentIdentity})}),result=await response.json();if(!response.ok||result.decision==='rejected')throw new Error(`Negotiation rejected: ${result.reason||JSON.stringify(result)}`);console.log(`Negotiation ${result.decision}: ${result.reason}`);return{agreed_price:result.final_price||result.counter_price,negotiation_id:result.negotiation_id}}
async function runBuyerAgent(goal){console.log(`\n=== Autonomous Buyer Agent ===\nGoal: ${goal}\n\nFetching catalog...`);const catalogResponse=await fetch(`${base}/api/catalog`);if(!catalogResponse.ok)throw new Error(`Catalog fetch failed: ${catalogResponse.status}`);const catalog=await catalogResponse.json();console.log(`Found ${catalog.products.length} products.\n\nAsking Gemini to decide...`);const decision=await decide(goal,catalog.products);console.log('Buyer agent decision:',decision);const pricing=await negotiate(decision,catalog);console.log('\nPlacing order via /api/order...');const response=await fetch(`${base}/api/order`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:decision.product_id,quantity:decision.quantity,size:decision.size,...pricing,actor:'autonomous_agent',agent_identity:agentIdentity,reasoning:`Goal: ${goal}. Decision (${decision.decision_source}): ${decision.reasoning}`})}),order=await response.json();if(!response.ok||!order.ok)throw new Error(`Order rejected (${response.status}): ${JSON.stringify(order)}`);console.log('✅ Order placed successfully:',order);return order}
runBuyerAgent(process.argv.slice(2).join(' ')||'Buy the cheapest in-stock running shoes, size 9').catch(error=>{console.error(error.message);process.exitCode=1});
