// Autonomous buyer: uses only the machine-readable catalog and order APIs.
if(!process.env.GEMINI_API_KEY){console.error('❌ GEMINI_API_KEY is not set. This script requires a real LLM to make purchasing decisions.');process.exit(1)}
const base=process.env.CARTWISE_URL||'http://127.0.0.1:8000';
async function decide(goal,products){
    const prompt=`You are an autonomous shopping agent acting on this exact goal: ${goal}\nCatalog: ${JSON.stringify(products)}\nEvaluate product name, category, description, price, sizes, and stock against the goal. Return ONLY JSON with product_id, quantity, size, reasoning. Choose exactly one in-stock product, quantity 1, and either a listed size or null when sizes are not applicable. Explain why it fits this specific goal.`;
    const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});
    if(!r.ok)throw new Error(`Gemini decision failed: ${r.status} ${await r.text()}`);const data=await r.json();const decision=JSON.parse(data.candidates?.[0]?.content?.parts?.[0]?.text||'');const selected=products.find(p=>p.id===decision.product_id);
    if(!selected||selected.stock<1||decision.quantity!==1||!decision.reasoning)throw new Error(`Gemini returned an invalid purchasing decision: ${JSON.stringify(decision)}`);
    if(decision.size!==null&&!selected.sizes.map(String).includes(String(decision.size)))throw new Error(`Gemini selected invalid size ${decision.size} for ${selected.id}`);
    return {...decision,decision_source:`Gemini (${model})`};
}
async function runBuyerAgent(goal){console.log(`\n=== Autonomous Buyer Agent ===\nGoal: ${goal}\n\nFetching catalog...`);const catalogResponse=await fetch(`${base}/api/catalog`);if(!catalogResponse.ok)throw new Error(`Catalog fetch failed: ${catalogResponse.status}`);const catalog=await catalogResponse.json();console.log(`Found ${catalog.products.length} products.\n\nAsking Gemini to decide...`);const decision=await decide(goal,catalog.products);console.log('Buyer agent decision:',decision);console.log('\nPlacing order via /api/order...');const orderResponse=await fetch(`${base}/api/order`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:decision.product_id,quantity:decision.quantity,size:decision.size,actor:'autonomous_agent',reasoning:`Goal: ${goal}. Decision (${decision.decision_source}): ${decision.reasoning}`})});const order=await orderResponse.json();if(!orderResponse.ok||!order.ok)throw new Error(`Order rejected (${orderResponse.status}): ${JSON.stringify(order)}`);console.log('✅ Order placed successfully:',order);return order}
runBuyerAgent(process.argv.slice(2).join(' ')||'Buy the cheapest in-stock running shoes, size 9').catch(error=>{console.error(error.message);process.exitCode=1});
